# Generated by Django 2.0.7 on 2018-07-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityfield',
            name='organization',
        ),
    ]
